project_name: nightride

builds:
  - id: nightride
    main: ./main.go
    binary: nightride
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64

archives:
  - format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - "{{ .Builds }}"

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: youruser # ⬅ Replace with your GitHub username
    name: nightride-cli
